{% set name = "gmx_MMPBSA" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 50b03f80f3efdcdd9132cd9c9bba975916f2ca5e89159ab37a720c7d04057a60

build:
  number: 0
  noarch: python
  entry_points:
    - gmx_MMPBSA = GMXMMPBSA.app:gmxmmpbsa
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pandas >=1.2.2
    - seaborn >=0.11.1
    - mpi4py >=3.1.3
    - scipy >=1.6.1
    - ambertools
    - matplotlib-base >=3.4.4
    - h5py

test:
  imports:
    - GMXMMPBSA
  requires:
    - pip
  commands:
    - pip check
    - gmx_MMPBSA -h

about:
  home: https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: gmx_MMPBSA is a new tool based on AMBER's MMPBSA.py aiming to perform end-state free energy calculations with GROMACS files.
  description: |
    gmx_MMPBSA is a new tool based on AMBER's MMPBSA.py aiming to perform end-state free energy calculations with 
    GROMACS files. It works with all GROMACS versions along with AmberTools20 or 21 and brings improvements in 
    compatibility, versatility, analyses, and parallelization compared to existing programs. 
    Multiple calculations can be performed with gmx_MMPBSA such as Normal binding free energies, Alanine scanning, 
    Decomposition schemes, Entropy corrections, Stability and QM/MMGBSA
  doc_url: https://valdes-tresanco-ms.github.io/gmx_MMPBSA
  dev_url: https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA

extra:
  recipe-maintainers:
    - Valdes-Tresanco-MS
    - marioernestovaldes
